---
title: "'Příkaz catch' bloku nedospělo, protože '<name1>'dědí z'<name2>."
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: fe716108281b3df64c3d444c54bee8dea3fcb82f
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/28/2019
ms.locfileid: "64755851"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>'Příkaz catch' bloku nedospělo, protože '\<name1 >' dědí z '\<name2 >'
A `Catch` nedospělo bloku kódu.  
  
 Ve výchozím nastavení tato zpráva je upozornění. Další informace o zobrazení nebo skrytí upozornění zpracování upozornění jako chyby, najdete v části [Konfigurace upozornění v jazyce Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID chyby:** BC42029  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
- Odebrat cizí `Catch` bloku.  
  
## <a name="see-also"></a>Viz také:

- [Postup používání bloku try/catch k zachycování výjimek](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
