---
title: "'Příkaz catch' bloku nedospělo, protože '<name1>\"dědí z\"<name2>."
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 89b916513633515ce5433d06e4cdda7039c688c3
ms.sourcegitcommit: 14355b4b2fe5bcf874cac96d0a9e6376b567e4c7
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 01/30/2019
ms.locfileid: "55289611"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>'Příkaz catch' bloku nedospělo, protože '\<name1 >' dědí z "\<name2 >"
A `Catch` nedospělo bloku kódu.  
  
 Ve výchozím nastavení tato zpráva je upozornění. Další informace o zobrazení nebo skrytí upozornění zpracování upozornění jako chyby, najdete v části [Konfigurace upozornění v jazyce Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID chyby:** BC42029  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
-   Odebrat cizí `Catch` bloku.  
  
## <a name="see-also"></a>Viz také:
- [Postupy: Testování kódu pomocí bloku Try... Blok catch v jazyce Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)
- [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
