---
ms.openlocfilehash: 94fad6fe910da6c528c5e13f529a6db274e07d5c
ms.sourcegitcommit: 5b6d778ebb269ee6684fb57ad69a8c28b06235b9
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 04/08/2019
ms.locfileid: "59235349"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="71206-101">Změna chování pro metody Task.WaitAll s argumenty časového limitu</span><span class="sxs-lookup"><span data-stu-id="71206-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

|   |   |
|---|---|
|<span data-ttu-id="71206-102">Podrobnosti</span><span class="sxs-lookup"><span data-stu-id="71206-102">Details</span></span>|<xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> <span data-ttu-id="71206-103">chování byla provedena konzistentnější v rozhraní .NET Framework 4.5.In rozhraní .NET Framework 4, tyto metody chovaly nekonzistentně.</span><span class="sxs-lookup"><span data-stu-id="71206-103">behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="71206-104">Po vypršení časového limitu, pokud jeden nebo více úlohy nebyly dokončeny nebo došlo ke zrušení před voláním metody, vyvolala metoda výjimku <xref:System.AggregateException?displayProperty=name> výjimky.</span><span class="sxs-lookup"><span data-stu-id="71206-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=name> exception.</span></span> <span data-ttu-id="71206-105">Pokud časový limit vypršel, když žádné úlohy nebyly dokončeny nebo došlo ke zrušení před voláním metody, ale jeden nebo více úloh zadalo tyto stavy po volání metody, metoda vrátila hodnotu false.</span><span class="sxs-lookup"><span data-stu-id="71206-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="71206-106">V rozhraní .NET Framework 4.5, tato přetížení metody nyní vrátí hodnotu false, pokud žádné úlohy jsou stále spuštěna, když uplynutím časového limitu, a generují výjimku <xref:System.AggregateException?displayProperty=name> výjimku pouze v případě, že vstupní úloha byla zrušena (bez ohledu na to, jestli byl před nebo po metodu volání) a jsou pořád spuštěné žádné úlohy.</span><span class="sxs-lookup"><span data-stu-id="71206-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=name> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>|
|<span data-ttu-id="71206-107">Doporučení</span><span class="sxs-lookup"><span data-stu-id="71206-107">Suggestion</span></span>|<span data-ttu-id="71206-108">Pokud <xref:System.AggregateException?displayProperty=name> se zachycení jako způsob zjišťování úlohu, která byla zrušena před verzí <xref:System.Threading.Tasks.Task.WaitAll%2A> volání volaná kód by měl místo toho proveďte stejné zjišťování prostřednictvím <xref:System.Threading.Tasks.Task.IsCanceled%2A> vlastnosti (například:. Any(t =&gt; t.IsCanceled)) od rozhraní .NET Framework 4.6 pouze vyvolá v takovém případě všechny očekávané úlohy jsou dokončeny před časový limit.</span><span class="sxs-lookup"><span data-stu-id="71206-108">If an <xref:System.AggregateException?displayProperty=name> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>|
|<span data-ttu-id="71206-109">Rozsah</span><span class="sxs-lookup"><span data-stu-id="71206-109">Scope</span></span>|<span data-ttu-id="71206-110">Vedlejší</span><span class="sxs-lookup"><span data-stu-id="71206-110">Minor</span></span>|
|<span data-ttu-id="71206-111">Version</span><span class="sxs-lookup"><span data-stu-id="71206-111">Version</span></span>|<span data-ttu-id="71206-112">4.5</span><span class="sxs-lookup"><span data-stu-id="71206-112">4.5</span></span>|
|<span data-ttu-id="71206-113">Type</span><span class="sxs-lookup"><span data-stu-id="71206-113">Type</span></span>|<span data-ttu-id="71206-114">Modul runtime</span><span class="sxs-lookup"><span data-stu-id="71206-114">Runtime</span></span>|
|<span data-ttu-id="71206-115">Ovlivněná rozhraní API</span><span class="sxs-lookup"><span data-stu-id="71206-115">Affected APIs</span></span>|<ul><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
